
const products = {
    products:[
         {
                id: 1,
                img:  "/images/pro1.jpg",
                title: "Couch",
                price: 10000,
                color: "Brown",
                aosDelay: "0",
            },
             {
                id: 2,
                img:  "/images/pro2.jpg",
                title: "Flower Vase",
                price: 1000,
                color: "Brown",
                aosDelay: "200",
            },
             {
                id: 3,
                img:  "/images/pro3.jpg",
                title: "Wall Art Frame",
                price: 3000,
                color: "Black & White",
                aosDelay: "400",
            },
             {
                id: 4,
                img:  "/images/pro4.jpg",
                title: "Hanging Lamp",
                price: 5000,
                color: "White",
                aosDelay: "600",
            },
             {
                id: 5,
                img:  "/images/pro5.jpg",
                title: "Wall Mount Shelf",
                price: 1000,
                color: "Ash-gray",
                aosDelay: "800",
            },
            {
                id: 6,
                img:  "/images/pro6.jpg",
                title: "Couch",
                price: 10000,
                color: "Gray",
                aosDelay: "0",
            },
             {
                id: 7,
                img:  "/images/pro7.jpg",
                title: "Flower Vase",
                price: 800,
                color: "white",
                aosDelay: "200",
            },
             {
                id: 8,
                img:  "/images/pro8.jpg",
                title: "Wall Art Frame",
                price: 2000,
                color: "Black & White",
                aosDelay: "400",
            },
             {
                id: 9,
                img:  "/images/pro9.jpg",
                title: "Hanging Lamp",
                price: 4500,
                color: "White",
                aosDelay: "600",
            },
             {
                id: 10,
                img:  "/images/pro10.jpg",
                title: "Wall Mount Shelf",
                price: 1500,
                color: "Ash-gray",
                aosDelay: "800",
            },
    ],
    furniture:[
          {
              id: 1,
              img: "/images/furniture1.jpg",
              title: "Modern Sofa",
              price:20000,
              description: "Comfortable sofa with premium fabric for your living room.",
            },
            {
              id: 2,
              img: "/images/furniture2.jpg",
              title: "Wooden Dining Table",
              price:30000,
              description: "Elegant dining table for family gatherings.",
            },
            {
              id: 3,
              img: "/images/furniture3.jpg",
              title: "Recliner Chair",
              price:15000,
              description: "Relaxing recliner with adjustable positions.",
            },
            {
              id: 4,
              img: "/images/furniture4.jpg",
              title: "Recliner Chair",
              price:12000,
              description: "Relaxing recliner with adjustable positions.",
            },
             {
              id: 5,
              img: "/images/furniture5.jpg",
              title: "Modern Sofa",
              price:25800,
              description: "Comfortable sofa with premium fabric for your living room.",
            },
             {
              id: 6,
              img: "/images/furniture6.jpg",
              title: "Comfy Mattress",
              price:98000,
              description: "Comfortable sofa with premium fabric for your Bed room.",
            },
    ],
    lamps:[
         {
            id: 1,
            img: "/images/lamp1.jpg",
            title: "Pendant Lamp",
            price:4000,
            description: "Stylish pendant lamp for ambient lighting.",
          },
          {
            id: 2,
            img: "/images/lamp2.jpg",
            title: "Floor Lamp",
            price:2000,
            description: "Tall floor lamp for reading corners.",
          },
          {
            id: 3,
            img: "/images/lamp3.jpg",
            title: "Table Lamp",
            price:2600,
            description: "Compact table lamp with adjustable shade.",
          },
          {
            id: 4,
            img: "/images/lamp4.jpg",
            title: "Pendant Lamp",
            price:7000,
            description: "Stylish pendant lamp for ambient lighting.",
          },
          {
            id: 5,
            img: "/images/lamp5.jpg",
            title: "Hanging Lamp",
            price:12000,
            description: "Tall floor lamp for reading corners.",
          },
          {
            id: 6,
            img: "/images/lamp6.jpg",
            title: "Hanging Lamp",
            price:19000,
            description: "Compact table lamp with adjustable shade.",
          },
    ],
    homedecor:[
        {
            id: 1,
            img: "/images/decor1.jpg",
            title: "Wall Art",
            price:6000,
            description: "Artistic wall decor to personalize your space.",
          },
          {
            id: 2,
            img: "/images/decor2.jpg",
            title: "Vase Set",
            price:4700,
            description: "Elegant vase set for floral arrangements.",
          },
          {
            id: 3,
            img: "/images/decor3.jpg",
            title: "Cushion Covers",
            price:2900,
            description: "Soft cushion covers with vibrant patterns.",
          },
          {
            id: 4,
            img: "/images/decor4.jpg",
            title: "Wall Art",
            price:6500,
            description: "Artistic wall decor to personalize your space.",
          },
          {
            id: 5,
            img: "/images/decor5.jpg",
            title: "Vase Set",
            price:1470,
            description: "Elegant vase set for floral arrangements.",
          },
          {
            id: 6,
            img: "/images/decor6.jpg",
            title: "Cushion Covers",
            price:1800,
            description: "Soft cushion covers with vibrant patterns.",
          },
    ],
    bestselling:[
         {
                id: 1,
                img: "/images/dec1.jpg",
                title: "Home Decor",
                price:50000,
                description: "Welcome the season with this handcrafted autumn wreath.it’s perfect for front doors or mantelpieces.",     
            },
            {
                id: 2,
                img: "/images/dec2.jpg",
                title: "Lamp",
                price:7000,
                description: "Add a touch of sophistication with this set of three pendant lamps.they cast a warm glow, ideal for dining areas or bedrooms.",     
            },
            {
                id: 3,
                img: "/images/dec3.jpg",
                title: "Elegant Couch",
                price:46000,
                description: "Elevate your living space with simple flower vase and comfy armchair with modern elegance",     
            },
            
    ],
};

module.exports = products;